config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friend_contacts
  #root 'home#index'
  root 'friend_contacts#index'
  get "home/about", to: "home#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend_contact.rb
class FriendContact < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friend_contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friend_contacts_controller.rb
class FriendContactsController < ApplicationController
  before_action :set_friend_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friend_contacts or /friend_contacts.json
  def index
    @friend_contacts = FriendContact.all
  end

  # GET /friend_contacts/1 or /friend_contacts/1.json
  def show
  end

  # GET /friend_contacts/new
  def new
    #@friend_contact = FriendContact.new
    @friend_contact = current_user.friend_contacts.build
  end

  # GET /friend_contacts/1/edit
  def edit
  end

  # POST /friend_contacts or /friend_contacts.json
  def create
    #@friend_contact = FriendContact.new(friend_contact_params)
    @friend_contact = current_user.friend_contacts.build(friend_contact_params)

    respond_to do |format|
      if @friend_contact.save
        format.html { redirect_to @friend_contact, notice: "Friend contact was successfully created." }
        format.json { render :show, status: :created, location: @friend_contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friend_contacts/1 or /friend_contacts/1.json
  def update
    respond_to do |format|
      if @friend_contact.update(friend_contact_params)
        format.html { redirect_to @friend_contact, notice: "Friend contact was successfully updated." }
        format.json { render :show, status: :ok, location: @friend_contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friend_contacts/1 or /friend_contacts/1.json
  def destroy
    @friend_contact.destroy
    respond_to do |format|
      format.html { redirect_to friend_contacts_url, notice: "Friend contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend_contact = current_user.friend_contacts.find_by(id: params[:id])
    redirect_to friend_contacts_path, notice: "Not Authorized to Edit this friend" if @friend_contact.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend_contact
      @friend_contact = FriendContact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_contact_params
      params.require(:friend_contact).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
    @about_me = "My name is Chit Nyi ....."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_contacts_helper.rb
module FriendContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friend_contacts/_form.html.erb
<%= form_with(model: friend_contact) do |form| %>
  <% if friend_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend_contact.errors.count, "error") %> prohibited this friend_contact from being saved:</h2>

      <ul>
        <% friend_contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :friend_contact_user_id, class:"form-control",
     value:current_user.id, type: :hidden %>
  </div>

  <br/>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friend_contacts/edit.html.erb
<h1>Editing Friend</h1>
<br/>
<%= render 'form', friend_contact: @friend_contact %>
<br/>
<%= link_to 'Show', @friend_contact, class:"btn btn-secondary" %> |
<%= link_to 'Destroy', @friend_contact, method: :delete, data: { confirm: 'Are you sure?' },
    class: "btn btn-danger" %> |
<%= link_to 'Back', friend_contacts_path, class:"btn btn-dark" %>

app/views/friend_contacts/index.html.erb
<% if user_signed_in? %>
  <table class="table table-striped table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @friend_contacts.each do |friend_contact| %>
        <% if friend_contact.user == current_user %>
          <tr>
            <td>
              <%= link_to friend_contact.first_name + ' ' + friend_contact.last_name, friend_contact %>
            </td>
            <td><%= friend_contact.email %></td>
            <td><%= friend_contact.phone %></td>
            <td><%= friend_contact.twitter %></td>
            <td>
              <%= link_to 'Destroy', friend_contact, method: :delete, data: { confirm: 'Are you sure?' },
               class: "btn btn-outline-danger btn-sm" %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Friend', new_friend_contact_path, class:'btn btn-secondary' %>
<% else %>
  Hello, Ruby On Rails Developer<br>
  Today is <%= Time.now.strftime('%A') %>.
<% end %>

app/views/friend_contacts/new.html.erb
<h1>Add New Friend</h1>
<br/>
<%= render 'form', friend_contact: @friend_contact %>
<br/>
<%= link_to 'Back', friend_contacts_path, class:"btn btn-dark" %>

app/views/friend_contacts/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend_contact.first_name %>
    <%= @friend_contact.last_name %>
  </h1>
  <p>
    <%= @friend_contact.email %> | <%= @friend_contact.phone %> | <%= @friend_contact.twitter %>
  </p>
  <br/>
  <br/>
  <%= link_to 'Edit', edit_friend_contact_path(@friend_contact), class:'btn btn-secondary' %> |
  <%= link_to 'Destroy', @friend_contact, method: :delete, data: { confirm: 'Are you sure?' },
    class: "btn btn-danger" %> |
  <%= link_to 'Back', friend_contacts_path, class:'btn btn-dark' %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Friend App', root_path, class:'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:'nav-link' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add Friend', new_friend_contact_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:'nav-link' %>
          </li>
        <% end %>
        
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us....</h1>

<p>
	<%= @about_me %>
</p>
<p>
	<% answer = 2 + 2 %>
	2 + 2 = <%= answer %>
</p>

app/views/home/index.html.erb
Hello, Ruby On Rails Developer<br>
<%#Today is Thursday.%>
Today is <%= Time.now.strftime('%A') %>.

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Friends App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <body>
    <%= render 'home/header' %>
    <div class="container">
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>